services:
    redis-1:
        image: redis
        command: ["redis-server","/etc/redis/redis.conf"]
        volumes:
            - ./node-1/data:/data
            - ./node-1/conf/redis.conf:/etc/redis/redis.conf
        ports:
            - 6371:6379
            - 16371:16379
        networks:
            redis_network:
                ipv4_address: 172.38.0.11

    redis-2:
      image: redis
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
        - ./node-2/data:/data
        - ./node-2/conf/redis.conf:/etc/redis/redis.conf
      ports:
        - "6372:6379"
        - 16372:16379
      networks:
        redis_network:
            ipv4_address: 172.38.0.12

    redis-3:
      image: redis
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
        - ./node-3/data:/data
        - ./node-3/conf/redis.conf:/etc/redis/redis.conf
      ports:
        - "6373:6379"
        - 16373:16379
      networks:
        redis_network:
            ipv4_address: 172.38.0.13

    redis-4:
      image: redis
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
          - ./node-4/data:/data
          - ./node-4/conf/redis.conf:/etc/redis/redis.conf
      ports:
          - "6374:6379"
          - 16374:16379
      networks:
          redis_network:
              ipv4_address: 172.38.0.14

    redis-5:
      image: redis
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
        - ./node-5/data:/data
        - ./node-5/conf/redis.conf:/etc/redis/redis.conf
      ports:
        - "6375:6379"
        - 16375:16379
      networks:
        redis_network:
            ipv4_address: 172.38.0.15

    redis-6:
      image: redis
      command: ["redis-server", "/etc/redis/redis.conf"]
      volumes:
        - ./node-6/data:/data
        - ./node-6/conf/redis.conf:/etc/redis/redis.conf
      ports:
        - "6376:6379"
        - "16376:16379"
      networks:
        redis_network:
            ipv4_address: 172.38.0.16

    redisinsight:
      image: redis/redisinsight:latest
      volumes:
        - ./redisinsight:/data
      ports:
        - 5540:5540
      networks:
        - redis_network

    sentinel-1:
      image: redis
      command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
      volumes:
        - ./sentinel-1/conf:/etc/redis
        - ./sentinel-1/data:/data
      ports:
        - 26379:26379
      networks:
        redis_network:
            ipv4_address: 172.38.0.21

    sentinel-2:
      image: redis
      command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
      volumes:
        - ./sentinel-2/conf:/etc/redis
        - ./sentinel-2/data:/data
      ports:
        - 26380:26379
      networks:
        redis_network:
            ipv4_address: 172.38.0.22

    sentinel-3:
      image: redis
      command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
      volumes:
        - ./sentinel-3/conf:/etc/redis
        - ./sentinel-3/data:/data
      ports:
        - 26381:26379
      networks:
        redis_network:
            ipv4_address: 172.38.0.23

networks:
    redis_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.38.0.0/16
                  gateway: 172.38.0.1
